### ISSUE TITLE
cannot find os-tmpdir is thrown from osenv.js

### ISSUE THREAD

**Issue by smartmouse** [npm/osenv#10]
# Error: Cannot find module 'os-tmpdir'

```
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/usr/lib/node_modules/apiconnect/node_modules/apiconnect-cli-logger/node_modules/osenv/osenv.js:4:16)
```

I was wondering what could cause this issue?

Do you rely on NODE_PATH to set up?
or you will require node install path in the $PATH? 
Looks like this issue is consistently happen when people is using NVM.

[root@kvm7rh61 ~]# apic
Error: Cannot find module 'os-homedir'
RHEL 7

[root@dpkvm7r1 ~]# apic
module.js:328
throw err;
^Error: Cannot find module 'os-tmpdir'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object. (/root/.nvm/versions/node/v4.2.6/lib/node_modules/apiconnect/node_modules/apiconnect-cli-logger/node_modules/osenv/osenv.js:4:16)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)

Thanks in advance.
It seems that setting NODE_PATH resolves the issue on some cases.

**Comment by isaacs** [comment]
How did you come to be using this module?  `os-tmpdir` is listed as a dependency, so it should get installed along with osenv.

If this was included as a dep of apiconnect-cli-logger, it seems like maybe npm installed a broken tree somehow?  What does `npm -v` output?

**Comment by ExtAnimal** [comment]
This just started happening for me.

npm broke itself.

I had to downgrade because something said it did not support npm 5, so of course I googled it, this being the modern world where nothing is documented and everything relies on online help *always* being available and correct.

So then I did

`~/react-native:$ npm install -g npm@latest-1`

And that busted it. npm won't run now.

**Comment by isaacs** [comment]
@ExtAnimal You've tried to install npm version 1.  I'm not surprised that is not going well, that version of npm is incredibly old and very much unsupported.

I recommend going to https://nodejs.org/ and installing wiht the big green button, or run `curl https://www.npmjs.com/install.sh | bash` to install just npm.  (You can also download and inspect the script before running it manually, if you don't like the curl|sh approach.)
